// qiankun-vue/src/App.vue
<template>
  <div id="app">
     <a-menu :selectedKeys="[currentRoute]" mode="horizontal" theme="dark">
      <a-menu-item
        v-for="(item) in menus"
        :key="item.key"
        >
        <router-link :to="item.route">{{item.title}}</router-link>
      </a-menu-item>
     </a-menu>
    <router-view :key="(new Date()).getTime()" />
  </div>
</template>

<script>
export default {
  name: 'App',
  data () {
    return {
      menus: [
        {
          key: 'vue',
          route: '/',
          title: '主页'
        },
        {
          key: 'vue-list',
          route: '/list',
          title: '列表页'
        }
      ]
    }
  },
  computed: {
    currentRoute () {
      const menu = this.menus.find(item => item.route === this.$route.path)
      return menu ? menu.key : 'vue'
    }
  }
}
</script>

<style>
</style>

// qiankun-angular/src/app/app.component.ts

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'micro-app-angular';

  menus = [
    {
      key: "angular",
      route: "/",
      title: "主页"
    },
    {
      key: "angular-list",
      route: "/list",
      title: "列表页"
    }
  ]

  get currentRoute() {
    const menu = this.menus.find(item => item.route === window.location.pathname)
    return menu ? menu.key : "angular";
  }
}
<section>
  <ul nz-menu nzMode="horizontal" nzTheme="dark">
    <li *ngFor="let item of menus" nz-menu-item [nzSelected]="currentRoute === item.key">
      <a [routerLink]="item.route">{{item.title}}</a>
    </li>
  </ul>
  
  <section style="padding: 20px;">
    <router-outlet></router-outlet>
  </section>
</section>
